# Generated by Django 2.1 on 2018-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jfile', models.FileField(upload_to='json_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10)),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['upload_date'],
                'verbose_name_plural': 'jfiles',
            },
        ),
    ]
